spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://wangxinbo.rwlb.rds.aliyuncs.com:3306/commodity?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: "Wb020211"
mybatis:
  configuration:
    # 将数据库字段名映射为驼峰命名
    map-underscore-to-camel-case: true
    # id自增长
    use-generated-keys: true
  # 自定义mybatis扫描包
  type-aliases-package: com.wxb.datalabel.entity
  # mybatis扫描mapper文件的位置
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
